CREATE DATABASE IF NOT EXISTS competitor_analyzer;
USE competitor_analyzer;

CREATE TABLE IF NOT EXISTS reports (
  id CHAR(36) NOT NULL PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  website TEXT NOT NULL,
  mode VARCHAR(20) NOT NULL DEFAULT 'standard',
  result JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
